### ISSUE TITLE
import cv2

### ISSUE THREAD

**Issue by jumpjack** [Kawaboongawa/Zolver#11]
Not working:

https://github.com/Kawaboongawa/Zolver/blob/c4ea07041e7fa617ebfe2c1cbf117eb345c7ce1e/src/Puzzle/Distance.py#L3

Working:

import cv2

(Win10, Python 3)

**Comment by simin75simin** [comment]
remove the 'from cv2' part and try again

**Comment by jeremy010203** [comment]
Fixed with latest version I close the issue
