### ISSUE TITLE
opencv_python==3.3.0.10 not found

### ISSUE THREAD

**Issue by synox** [Kawaboongawa/Zolver#2]
ERROR: Could not find a version that satisfies the requirement opencv_python==3.3.0.10 (from -r requirements.txt (line 3)) (from versions: 3.4.2.16, 3.4.2.17, 3.4.3.18, 3.4.4.19, 3.4.5.20, 3.4.6.27, 3.4.7.28, 3.4.8.29, 4.0.0.21, 4.0.1.24, 4.1.0.25, 4.1.1.26, 4.1.2.30)
ERROR: No matching distribution found for opencv_python==3.3.0.10 (from -r requirements.txt (line 3))

using python 3.7

**Comment by FlaviusBejan** [comment]
Try this in requirements.txt:
`numpy==1.17.3
scipy==1.4.0
opencv_python==3.4.8.29
opencv-contrib-python==3.4.8.29
scikit_image==0.14.2
matplotlib==2.2.5
Pillow
PyQt5>=5.0
scikit_learn>=0.18.1
`

**Comment by simin75simin** [comment]
got it to work by using python3.7.9, opencv_python<3.5

**Comment by jeremy010203** [comment]
Requirements updated with latest version I close the issue
