### ISSUE TITLE
Getting an error when running.

### ISSUE THREAD

**Issue by PrinceOfParallax** [Kawaboongawa/Zolver#9]
![image](https://user-images.githubusercontent.com/38820735/154700447-4423d55a-cde2-472a-b0ea-c8f041d6c7fc.png)

**Comment by jumpjack** [comment]
Did you find a solution?

**Comment by simin75simin** [comment]
opencv version too new, remove the third parameter so it's like this:

```_, contour = cv2.findContours(self.img_bw, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_SIMPLE)```
P.S. you need to do it once again on a later line:

```self.img_bw, contours = cv2.findContours(self.img_bw, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)```

**Comment by jeremy010203** [comment]
Fixed with latest version I close the issue
